### PR TITLE
Updated company_ids.json

### PR DESCRIPTION
**Pull request by dinesharjani**

### CODE REVIEW

**Comment by eriklins** [comment]
There is an empty entry 3619, which - I think - should be removed. It's also missing in the original BT SiG YAML file: https://bitbucket.org/bluetooth-SIG/public/src/main/assigned_numbers/company_identifiers/company_identifiers.yaml (0x0E23 has not been assigned, not sure why).

**Comment by dinesharjani** [comment]
> There is an empty entry 3619, which - I think - should be removed. It's also missing in the original BT SiG YAML file: https://bitbucket.org/bluetooth-SIG/public/src/main/assigned_numbers/company_identifiers/company_identifiers.yaml (0x0E23 has not been assigned, not sure why).

What a keen eye! I just... yeah, I added it because I don't like the gaps being there. But I guess you're right.

**Review by eriklins — APPROVED** [review]
Looks good now from my perspective.

**Comment by dinesharjani** [comment]
Hey @eriklins - I'm going to keep 3619 as "Reserved". There's already the precedent of one of these missing IDs to get assigned later. I think it makes sense to keep it. It might never be used, but we can decide later if we keep getting these skips in the Company ID list and modify the scripts to accommodate them.

**Comment by eriklins** [comment]
Yeah, now as you mention that, I had added this to the Python script I sent to you a while back. It actually inserts a "Reserved" entry on missing entries.

**Comment by dinesharjani** [comment]
> Yeah, now as you mention that, I had added this to the Python script I sent to you a while back. It actually inserts a "Reserved" entry on missing entries.

Oh. Okay. Going to look at that now, since I'm here.

**Comment by dinesharjani** [comment]
Okay, so. I see your script here https://github.com/eriklins/bt-assigned-numbers-to-c-header/blob/main/bt_assigned_numbers_to_c.py

My only issue with it, is that it's Python. Now, I'm not a "web developer". This project is in Node.js because when I built it, the other developers at Nordic that lent me a hand suggested Node.js. Since most of this is node.js, and the Github actions are set up to run node.js, I think the best way to keep this project going forward is to keep it in Node.js / JavaScript. Not sure if I want to tackle writing the whole thing in Javascript now, though I could try feeding it to some ... "artificial intellgence". But I just wanted to come back to you and tell you where my head's at.

**Pull request merged**
