### PR TITLE
Added JSON file with GAP appearance values from BT SiG

### PR DESCRIPTION
**Pull request by eriklins**
As discussed with @dinesharjani in #106 here is my pull-request with gap_appearance.json file. This file has been automatically created from BT SiG bitbucket url  @https://bitbucket.org/bluetooth-SIG/public/src/main/assigned_numbers/core/appearance_values.yaml with an own [Python script](https://github.com/NordicSemiconductor/bluetooth-numbers-database/files/13818905/GapAppearanceToJson.zip). I did not modify any of the existing JS scripts since I couldn't fully figure which do what. I'm happy to update the appearance values on a regular basis, if need be.

### CODE REVIEW

**Comment by dinesharjani** [comment]
@eriklins Thanks! I'll have a look tomorrow if that's okay.

**Comment by dinesharjani** [comment]
@eriklins All okay. You just need to accept the CLA

**Review by dinesharjani — APPROVED** [review]

**Comment by philips77** [comment]
Hello,
You need to set the same e-mail address in Git for the commit you did. From GitHub perspective you, who did the commit (no e-mail) and you, who opened PR, are different people. The e-mail needs to match.
Have a look at [this](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-email-address-for-every-repository-on-your-computer).

**Comment by eriklins** [comment]
How can I check which email has been used for the commit? I cannot recall setting any other email address than which is already in my email settings. Git log shows:

2024-01-10 12_10_22-Total Commander (x64) 11 00 - Erik Lins

No email address but just my username.

**Comment by dinesharjani** [comment]
So you can ammend your commit with your correct username and then git push -f to the branch with this PR

**Comment by eriklins** [comment]
Thanks for the help Dinesh and Aleksander, seems it did work now.

**Comment by dinesharjani** [comment]
@eriklins thanks to you. Sorry about the delay regarding looking into this, because I had a swamp of other work things

**Pull request merged**
