### PR TITLE
updated company ids

### PR DESCRIPTION
**Pull request by eriklins**
updated company_ids.json from https://bitbucket.org/bluetooth-SIG/public/src/main/assigned_numbers/company_identifiers/company_identifiers.yaml

### CODE REVIEW

**Comment by eriklins** [comment]
Looks like company id 1048 (0x418) is missing in the original BT SiG list: https://bitbucket.org/bluetooth-SIG/public/src/main/assigned_numbers/company_identifiers/company_identifiers.yaml. Those seem have to be added to the json (manually?) as "Reserved". However, not sure if this is the proper way and there should be no issue with a gap in the numbering, since the original BT SiG document also have this gap. Any thougths?

**Comment by dinesharjani** [comment]
So, you removed code 65535 from the list.

**Comment by eriklins** [comment]
Thanks for following up.  added 1048 and 3271 as "Reserved" and also added the missing 65535.

**Review by dinesharjani — APPROVED** [review]

**Comment by dinesharjani** [comment]
Thank you very much for @eriklins for this PR. May I ask, did you write this "by hand" or did you write a script of some sort to generate the changes?

**Comment by eriklins** [comment]
Hello @dinesharjani, thanks for approving the pull-request - much appreciated.

I wrote a small Python script to create that JSON file from the original BT SiG company ids JAML file on Bitbucket, see attached. The latest version looks for missing ids like the above 1048 and 2371 and inserts "Reserved" entries for those. However, the current version just works for one missing id, if the YAML would be missing two or more consecutively, it won't work (not tested).

[company_ids_to_json.zip](https://github.com/user-attachments/files/16747552/company_ids_to_json.zip)

**Comment by dinesharjani** [comment]
Great! I have a starting point if I ever get the time to write an automated GitHub Action. Thanks!

**Pull request merged**
