### PR TITLE
Update company_ids.json

### PR DESCRIPTION
**Pull request by ysoyipek**
from https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers/

### CODE REVIEW

**Comment by dinesharjani** [comment]
@ysoyipek thank you very much! Did you write a script to pull from the Bluetooth website or something?

**Comment by ysoyipek** [comment]
> @ysoyipek thank you very much! Did you write a script to pull from the Bluetooth website or something?

we have an api service that we code for our own api services. We wanted to make the update after we registered. I added it to the periodic task list. It will send the update monthly.

**Comment by epac-tom** [comment]
@ysoyipek do I understand you correctly, you're service will create a PR each month with the updates?
I was planning on creating a PR, our ID was recently added to the list, but if your service is due to run automatically I just hold off.

**Comment by dinesharjani** [comment]
@epac-tom I can do a PR and update the Company ID listing if you'd like. You can also add it yourself and I'll approve it.

**Comment by epac-tom** [comment]
@dinesharjani thanks, I'll update the list and push through a PR.

**Comment by dinesharjani** [comment]
@epac-tom no problem. I'll try to be on the lookout today for your PR. Add me as reviewer / or tag me so I see it in my inbox.

**Pull request merged**
